### ISSUE TITLE
Data is not bound in list view

### ISSUE THREAD

**Issue by dawoe** [jamiepollock/Umbraco-MigrationsViewer#1]
The data binding is not happening correctly.
I see a row for all my records, but no data in them

![migrations viewer](https://cloud.githubusercontent.com/assets/1193822/15960453/336fa32a-2f00-11e6-82b3-dae7c98c9146.png)

This is easily fixed by changing the view

```
 <tbody>
<tr ng-repeat="item in items">
     <td>{{item.Version}}</td>
     <td>{{item.CreateDate}}</td>
</tr>
</tbody>
```

The Api returns the properties starting with a uppercase letter

**Comment by jamiepollock** [comment]
Haha, bizarre! I've had it return lowercase locally. I think I'm going to have to add the [JsonCamelCaseFormatter](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/WebApi/JsonCamelCaseFormatter.cs) filter attribute on to ensure it's consistent. I'll get a fix in added after lunch :)

**Comment by jamiepollock** [comment]
I'm fairly new to this, what would be the best way to test this? Could I provide the nuspec from the appveyor build and you could test locally? I don't have a myget feed at this point.

**Comment by jamiepollock** [comment]
@dawoe maybe because I'm mad with power or perhaps I don't know any better I've released [a new version ](https://www.nuget.org/packages/Our.Umbraco.MigrationsViewer)which should fix the issues you're having here. 

Could you update to the latest nuget package and see if it fixes this?

**Comment by jamiepollock** [comment]
@dawoe Looks like I was super hasty about using JsonCamelCaseFormatter. Turns out [it's causing issues](http://issues.umbraco.org/issue/U4-8614) with other Controllers returning JSON.

I've [removed it](https://github.com/jamiepollock/Umbraco-MigrationsViewer/commit/a447cabf99901cd8e2e1cdd91c19f9553549c09f) now, but if people are using JsonCamelCaseFormatter in their own code it will cause an issue.

**Comment by jamiepollock** [comment]
Closing this issue for now as this was an issue using JsonCamelCaseFormatter in the target website. Now I've removed it from this package's code and implemented @dawoe's original suggestion.
